/*
 * Extra derived tables for MS Access app queries, not originaly from OLE.
 *
 * We are lazy about defining the columns...
 */

/*
 * marc_field_880
 * Only the 880 fields, supports non-Roman queries, e.g. in Pull List
 */
DROP TABLE local_ole.marctab_field_880;
CREATE TABLE local_ole.marctab_field_880 AS SELECT * FROM folio_source_record.marc__t WHERE field = '880';
CREATE INDEX ON local_ole.marctab_field_880 (instance_hrid);
CREATE INDEX ON local_ole.marctab_field_880 (sf);
VACUUM ANALYZE local_ole.marctab_field_880;

/* Countries */
DROP TABLE IF EXISTS local_ole.uc_countries;
CREATE TABLE local_ole.uc_countries (
    alpha2_code character varying(2) NOT NULL,
    alpha3_code character varying(3) NOT NULL,
    name character varying(128) NOT NULL
);
INSERT INTO local_ole.uc_countries (alpha2_code, alpha3_code, name) VALUES ('AD','AND','Andorra');
INSERT INTO local_ole.uc_countries (alpha2_code, alpha3_code, name) VALUES ('AE','ARE','United Arab Emirates');
INSERT INTO local_ole.uc_countries (alpha2_code, alpha3_code, name) VALUES ('AF','AFG','Afghanistan');
INSERT INTO local_ole.uc_countries (alpha2_code, alpha3_code, name) VALUES ('AG','ATG','Antigua and Barbuda');
INSERT INTO local_ole.uc_countries (alpha2_code, alpha3_code, name) VALUES ('AI','AIA','Anguilla');
INSERT INTO local_ole.uc_countries (alpha2_code, alpha3_code, name) VALUES ('AL','ALB','Albania');
INSERT INTO local_ole.uc_countries (alpha2_code, alpha3_code, name) VALUES ('AM','ARM','Armenia');
INSERT INTO local_ole.uc_countries (alpha2_code, alpha3_code, name) VALUES ('AN','ANT','Netherlands Antilles');
INSERT INTO local_ole.uc_countries (alpha2_code, alpha3_code, name) VALUES ('AO','AGO','Angola');
INSERT INTO local_ole.uc_countries (alpha2_code, alpha3_code, name) VALUES ('AQ','ATA','Antarctica');
INSERT INTO local_ole.uc_countries (alpha2_code, alpha3_code, name) VALUES ('AR','ARG','Argentina');
INSERT INTO local_ole.uc_countries (alpha2_code, alpha3_code, name) VALUES ('AS','ASM','American Samoa');
INSERT INTO local_ole.uc_countries (alpha2_code, alpha3_code, name) VALUES ('AT','AUT','Austria');
INSERT INTO local_ole.uc_countries (alpha2_code, alpha3_code, name) VALUES ('AU','AUS','Australia');
INSERT INTO local_ole.uc_countries (alpha2_code, alpha3_code, name) VALUES ('AW','ABW','Aruba');
INSERT INTO local_ole.uc_countries (alpha2_code, alpha3_code, name) VALUES ('AX','ALA','Åland Islands');
INSERT INTO local_ole.uc_countries (alpha2_code, alpha3_code, name) VALUES ('AZ','AZE','Azerbaijan');
INSERT INTO local_ole.uc_countries (alpha2_code, alpha3_code, name) VALUES ('BA','BIH','Bosnia and Herzegovina');
INSERT INTO local_ole.uc_countries (alpha2_code, alpha3_code, name) VALUES ('BB','BRB','Barbados');
INSERT INTO local_ole.uc_countries (alpha2_code, alpha3_code, name) VALUES ('BD','BGD','Bangladesh');
INSERT INTO local_ole.uc_countries (alpha2_code, alpha3_code, name) VALUES ('BE','BEL','Belgium');
INSERT INTO local_ole.uc_countries (alpha2_code, alpha3_code, name) VALUES ('BF','BFA','Burkina Faso');
INSERT INTO local_ole.uc_countries (alpha2_code, alpha3_code, name) VALUES ('BG','BGR','Bulgaria');
INSERT INTO local_ole.uc_countries (alpha2_code, alpha3_code, name) VALUES ('BH','BHR','Bahrain');
INSERT INTO local_ole.uc_countries (alpha2_code, alpha3_code, name) VALUES ('BI','BDI','Burundi');
INSERT INTO local_ole.uc_countries (alpha2_code, alpha3_code, name) VALUES ('BJ','BEN','Benin');
INSERT INTO local_ole.uc_countries (alpha2_code, alpha3_code, name) VALUES ('BL','BLM','Saint Barthélemy');
INSERT INTO local_ole.uc_countries (alpha2_code, alpha3_code, name) VALUES ('BM','BMU','Bermuda');
INSERT INTO local_ole.uc_countries (alpha2_code, alpha3_code, name) VALUES ('BN','BRN','Brunei Darussalam');
INSERT INTO local_ole.uc_countries (alpha2_code, alpha3_code, name) VALUES ('BO','BOL','Bolivia, Plurinational State Of');
INSERT INTO local_ole.uc_countries (alpha2_code, alpha3_code, name) VALUES ('BR','BRA','Brazil');
INSERT INTO local_ole.uc_countries (alpha2_code, alpha3_code, name) VALUES ('BS','BHS','Bahamas');
INSERT INTO local_ole.uc_countries (alpha2_code, alpha3_code, name) VALUES ('BT','BTN','Bhutan');
INSERT INTO local_ole.uc_countries (alpha2_code, alpha3_code, name) VALUES ('BV','BVT','Bouvet Island');
INSERT INTO local_ole.uc_countries (alpha2_code, alpha3_code, name) VALUES ('BW','BWA','Botswana');
INSERT INTO local_ole.uc_countries (alpha2_code, alpha3_code, name) VALUES ('BY','BLR','Belarus');
INSERT INTO local_ole.uc_countries (alpha2_code, alpha3_code, name) VALUES ('BZ','BLZ','Belize');
INSERT INTO local_ole.uc_countries (alpha2_code, alpha3_code, name) VALUES ('CA','CAN','Canada');
INSERT INTO local_ole.uc_countries (alpha2_code, alpha3_code, name) VALUES ('CC','CCK','Cocos (Keeling), Islands');
INSERT INTO local_ole.uc_countries (alpha2_code, alpha3_code, name) VALUES ('CD','COD','Congo, The Democratic Republic Of The');
INSERT INTO local_ole.uc_countries (alpha2_code, alpha3_code, name) VALUES ('CF','CAF','Central African Republic');
INSERT INTO local_ole.uc_countries (alpha2_code, alpha3_code, name) VALUES ('CG','COG','Congo');
INSERT INTO local_ole.uc_countries (alpha2_code, alpha3_code, name) VALUES ('CH','CHE','Switzerland');
INSERT INTO local_ole.uc_countries (alpha2_code, alpha3_code, name) VALUES ('CI','CIV','Côte D''Ivoire');
INSERT INTO local_ole.uc_countries (alpha2_code, alpha3_code, name) VALUES ('CK','COK','Cook Islands');
INSERT INTO local_ole.uc_countries (alpha2_code, alpha3_code, name) VALUES ('CL','CHL','Chile');
INSERT INTO local_ole.uc_countries (alpha2_code, alpha3_code, name) VALUES ('CM','CMR','Cameroon');
INSERT INTO local_ole.uc_countries (alpha2_code, alpha3_code, name) VALUES ('CN','CHN','China');
INSERT INTO local_ole.uc_countries (alpha2_code, alpha3_code, name) VALUES ('CO','COL','Colombia');
INSERT INTO local_ole.uc_countries (alpha2_code, alpha3_code, name) VALUES ('CR','CRI','Costa Rica');
INSERT INTO local_ole.uc_countries (alpha2_code, alpha3_code, name) VALUES ('CU','CUB','Cuba');
INSERT INTO local_ole.uc_countries (alpha2_code, alpha3_code, name) VALUES ('CV','CPV','Cape Verde');
INSERT INTO local_ole.uc_countries (alpha2_code, alpha3_code, name) VALUES ('CX','CXR','Christmas Island');
INSERT INTO local_ole.uc_countries (alpha2_code, alpha3_code, name) VALUES ('CY','CYP','Cyprus');
INSERT INTO local_ole.uc_countries (alpha2_code, alpha3_code, name) VALUES ('CZ','CZE','Czech Republic');
INSERT INTO local_ole.uc_countries (alpha2_code, alpha3_code, name) VALUES ('DE','DEU','Germany');
INSERT INTO local_ole.uc_countries (alpha2_code, alpha3_code, name) VALUES ('DJ','DJI','Djibouti');
INSERT INTO local_ole.uc_countries (alpha2_code, alpha3_code, name) VALUES ('DK','DNK','Denmark');
INSERT INTO local_ole.uc_countries (alpha2_code, alpha3_code, name) VALUES ('DM','DMA','Dominica');
INSERT INTO local_ole.uc_countries (alpha2_code, alpha3_code, name) VALUES ('DO','DOM','Dominican Republic');
INSERT INTO local_ole.uc_countries (alpha2_code, alpha3_code, name) VALUES ('DZ','DZA','Algeria');
INSERT INTO local_ole.uc_countries (alpha2_code, alpha3_code, name) VALUES ('EC','ECU','Ecuador');
INSERT INTO local_ole.uc_countries (alpha2_code, alpha3_code, name) VALUES ('EE','EST','Estonia');
INSERT INTO local_ole.uc_countries (alpha2_code, alpha3_code, name) VALUES ('EG','EGY','Egypt');
INSERT INTO local_ole.uc_countries (alpha2_code, alpha3_code, name) VALUES ('EH','ESH','Western Sahara');
INSERT INTO local_ole.uc_countries (alpha2_code, alpha3_code, name) VALUES ('ER','ERI','Eritrea');
INSERT INTO local_ole.uc_countries (alpha2_code, alpha3_code, name) VALUES ('ES','ESP','Spain');
INSERT INTO local_ole.uc_countries (alpha2_code, alpha3_code, name) VALUES ('ET','ETH','Ethiopia');
INSERT INTO local_ole.uc_countries (alpha2_code, alpha3_code, name) VALUES ('FI','FIN','Finland');
INSERT INTO local_ole.uc_countries (alpha2_code, alpha3_code, name) VALUES ('FJ','FJI','Fiji');
INSERT INTO local_ole.uc_countries (alpha2_code, alpha3_code, name) VALUES ('FK','FLK','Falkland Islands (Malvinas),');
INSERT INTO local_ole.uc_countries (alpha2_code, alpha3_code, name) VALUES ('FM','FSM','Micronesia, Federated States Of');
INSERT INTO local_ole.uc_countries (alpha2_code, alpha3_code, name) VALUES ('FO','FRO','Faroe Islands');
INSERT INTO local_ole.uc_countries (alpha2_code, alpha3_code, name) VALUES ('FR','FRA','France');
INSERT INTO local_ole.uc_countries (alpha2_code, alpha3_code, name) VALUES ('GA','GAB','Gabon');
INSERT INTO local_ole.uc_countries (alpha2_code, alpha3_code, name) VALUES ('GB','GBR','United Kingdom');
INSERT INTO local_ole.uc_countries (alpha2_code, alpha3_code, name) VALUES ('GD','GRD','Grenada');
INSERT INTO local_ole.uc_countries (alpha2_code, alpha3_code, name) VALUES ('GE','GEO','Georgia');
INSERT INTO local_ole.uc_countries (alpha2_code, alpha3_code, name) VALUES ('GF','GUF','French Guiana');
INSERT INTO local_ole.uc_countries (alpha2_code, alpha3_code, name) VALUES ('GG','GGY','Guernsey');
INSERT INTO local_ole.uc_countries (alpha2_code, alpha3_code, name) VALUES ('GH','GHA','Ghana');
INSERT INTO local_ole.uc_countries (alpha2_code, alpha3_code, name) VALUES ('GI','GIB','Gibraltar');
INSERT INTO local_ole.uc_countries (alpha2_code, alpha3_code, name) VALUES ('GL','GRL','Greenland');
INSERT INTO local_ole.uc_countries (alpha2_code, alpha3_code, name) VALUES ('GM','GMB','Gambia');
INSERT INTO local_ole.uc_countries (alpha2_code, alpha3_code, name) VALUES ('GN','GIN','Guinea');
INSERT INTO local_ole.uc_countries (alpha2_code, alpha3_code, name) VALUES ('GP','GLP','Guadeloupe');
INSERT INTO local_ole.uc_countries (alpha2_code, alpha3_code, name) VALUES ('GQ','GNQ','Equatorial Guinea');
INSERT INTO local_ole.uc_countries (alpha2_code, alpha3_code, name) VALUES ('GR','GRC','Greece');
INSERT INTO local_ole.uc_countries (alpha2_code, alpha3_code, name) VALUES ('GS','SGS','South Georgia and South Sandwich Islands');
INSERT INTO local_ole.uc_countries (alpha2_code, alpha3_code, name) VALUES ('GT','GTM','Guatemala');
INSERT INTO local_ole.uc_countries (alpha2_code, alpha3_code, name) VALUES ('GU','GUM','Guam');
INSERT INTO local_ole.uc_countries (alpha2_code, alpha3_code, name) VALUES ('GW','GNB','Guinea-Bissau');
INSERT INTO local_ole.uc_countries (alpha2_code, alpha3_code, name) VALUES ('GY','GUY','Guyana');
INSERT INTO local_ole.uc_countries (alpha2_code, alpha3_code, name) VALUES ('HK','HKG','Hong Kong');
INSERT INTO local_ole.uc_countries (alpha2_code, alpha3_code, name) VALUES ('HM','HMD','Heard and McDonald Islands');
INSERT INTO local_ole.uc_countries (alpha2_code, alpha3_code, name) VALUES ('HN','HND','Honduras');
INSERT INTO local_ole.uc_countries (alpha2_code, alpha3_code, name) VALUES ('HR','HRV','Croatia');
INSERT INTO local_ole.uc_countries (alpha2_code, alpha3_code, name) VALUES ('HT','HTI','Haiti');
INSERT INTO local_ole.uc_countries (alpha2_code, alpha3_code, name) VALUES ('HU','HUN','Hungary');
INSERT INTO local_ole.uc_countries (alpha2_code, alpha3_code, name) VALUES ('ID','IDN','Indonesia');
INSERT INTO local_ole.uc_countries (alpha2_code, alpha3_code, name) VALUES ('IE','IRL','Ireland');
INSERT INTO local_ole.uc_countries (alpha2_code, alpha3_code, name) VALUES ('IL','ISR','Israel');
INSERT INTO local_ole.uc_countries (alpha2_code, alpha3_code, name) VALUES ('IM','IMN','Isle of Man');
INSERT INTO local_ole.uc_countries (alpha2_code, alpha3_code, name) VALUES ('IN','IND','India');
INSERT INTO local_ole.uc_countries (alpha2_code, alpha3_code, name) VALUES ('IO','IOT','British Indian Ocean Territory');
INSERT INTO local_ole.uc_countries (alpha2_code, alpha3_code, name) VALUES ('IQ','IRQ','Iraq');
INSERT INTO local_ole.uc_countries (alpha2_code, alpha3_code, name) VALUES ('IR','IRN','Iran, Islamic Republic Of');
INSERT INTO local_ole.uc_countries (alpha2_code, alpha3_code, name) VALUES ('IS','ISL','Iceland');
INSERT INTO local_ole.uc_countries (alpha2_code, alpha3_code, name) VALUES ('IT','ITA','Italy');
INSERT INTO local_ole.uc_countries (alpha2_code, alpha3_code, name) VALUES ('JE','JEY','Jersey');
INSERT INTO local_ole.uc_countries (alpha2_code, alpha3_code, name) VALUES ('JM','JAM','Jamaica');
INSERT INTO local_ole.uc_countries (alpha2_code, alpha3_code, name) VALUES ('JO','JOR','Jordan');
INSERT INTO local_ole.uc_countries (alpha2_code, alpha3_code, name) VALUES ('JP','JPN','Japan');
INSERT INTO local_ole.uc_countries (alpha2_code, alpha3_code, name) VALUES ('KE','KEN','Kenya');
INSERT INTO local_ole.uc_countries (alpha2_code, alpha3_code, name) VALUES ('KG','KGZ','Kyrgyzstan');
INSERT INTO local_ole.uc_countries (alpha2_code, alpha3_code, name) VALUES ('KH','KHM','Cambodia');
INSERT INTO local_ole.uc_countries (alpha2_code, alpha3_code, name) VALUES ('KI','KIR','Kiribati');
INSERT INTO local_ole.uc_countries (alpha2_code, alpha3_code, name) VALUES ('KM','COM','Comoros');
INSERT INTO local_ole.uc_countries (alpha2_code, alpha3_code, name) VALUES ('KN','KNA','Saint Kitts And Nevis');
INSERT INTO local_ole.uc_countries (alpha2_code, alpha3_code, name) VALUES ('KP','PRK','Korea, Democratic People''s Republic Of');
INSERT INTO local_ole.uc_countries (alpha2_code, alpha3_code, name) VALUES ('KR','KOR','Korea, Republic of');
INSERT INTO local_ole.uc_countries (alpha2_code, alpha3_code, name) VALUES ('KW','KWT','Kuwait');
INSERT INTO local_ole.uc_countries (alpha2_code, alpha3_code, name) VALUES ('KY','CYM','Cayman Islands');
INSERT INTO local_ole.uc_countries (alpha2_code, alpha3_code, name) VALUES ('KZ','KAZ','Kazakhstan');
INSERT INTO local_ole.uc_countries (alpha2_code, alpha3_code, name) VALUES ('LA','LAO','Lao People''s Democratic Republic');
INSERT INTO local_ole.uc_countries (alpha2_code, alpha3_code, name) VALUES ('LB','LBN','Lebanon');
INSERT INTO local_ole.uc_countries (alpha2_code, alpha3_code, name) VALUES ('LC','LCA','Saint Lucia');
INSERT INTO local_ole.uc_countries (alpha2_code, alpha3_code, name) VALUES ('LI','LIE','Liechtenstein');
INSERT INTO local_ole.uc_countries (alpha2_code, alpha3_code, name) VALUES ('LK','LKA','Sri Lanka');
INSERT INTO local_ole.uc_countries (alpha2_code, alpha3_code, name) VALUES ('LR','LBR','Liberia');
INSERT INTO local_ole.uc_countries (alpha2_code, alpha3_code, name) VALUES ('LS','LSO','Lesotho');
INSERT INTO local_ole.uc_countries (alpha2_code, alpha3_code, name) VALUES ('LT','LTU','Lithuania');
INSERT INTO local_ole.uc_countries (alpha2_code, alpha3_code, name) VALUES ('LU','LUX','Luxembourg');
INSERT INTO local_ole.uc_countries (alpha2_code, alpha3_code, name) VALUES ('LV','LVA','Latvia');
INSERT INTO local_ole.uc_countries (alpha2_code, alpha3_code, name) VALUES ('LY','LBY','Libyan Arab Jamahiriya');
INSERT INTO local_ole.uc_countries (alpha2_code, alpha3_code, name) VALUES ('MA','MAR','Morocco');
INSERT INTO local_ole.uc_countries (alpha2_code, alpha3_code, name) VALUES ('MC','MCO','Monaco');
INSERT INTO local_ole.uc_countries (alpha2_code, alpha3_code, name) VALUES ('MD','MDA','Moldova, Republic of');
INSERT INTO local_ole.uc_countries (alpha2_code, alpha3_code, name) VALUES ('ME','MNE','Montenegro');
INSERT INTO local_ole.uc_countries (alpha2_code, alpha3_code, name) VALUES ('MF','MAF','Saint Martin');
INSERT INTO local_ole.uc_countries (alpha2_code, alpha3_code, name) VALUES ('MG','MDG','Madagascar');
INSERT INTO local_ole.uc_countries (alpha2_code, alpha3_code, name) VALUES ('MH','MHL','Marshall Islands');
INSERT INTO local_ole.uc_countries (alpha2_code, alpha3_code, name) VALUES ('MK','MKD','Macedonia, the Fmr. Yugoslav Republic Of');
INSERT INTO local_ole.uc_countries (alpha2_code, alpha3_code, name) VALUES ('ML','MLI','Mali');
INSERT INTO local_ole.uc_countries (alpha2_code, alpha3_code, name) VALUES ('MM','MMR','Myanmar');
INSERT INTO local_ole.uc_countries (alpha2_code, alpha3_code, name) VALUES ('MN','MNG','Mongolia');
INSERT INTO local_ole.uc_countries (alpha2_code, alpha3_code, name) VALUES ('MO','MAC','Macao');
INSERT INTO local_ole.uc_countries (alpha2_code, alpha3_code, name) VALUES ('MP','MNP','Northern Mariana Islands');
INSERT INTO local_ole.uc_countries (alpha2_code, alpha3_code, name) VALUES ('MQ','MTQ','Martinique');
INSERT INTO local_ole.uc_countries (alpha2_code, alpha3_code, name) VALUES ('MR','MRT','Mauritania');
INSERT INTO local_ole.uc_countries (alpha2_code, alpha3_code, name) VALUES ('MS','MSR','Montserrat');
INSERT INTO local_ole.uc_countries (alpha2_code, alpha3_code, name) VALUES ('MT','MLT','Malta');
INSERT INTO local_ole.uc_countries (alpha2_code, alpha3_code, name) VALUES ('MU','MUS','Mauritius');
INSERT INTO local_ole.uc_countries (alpha2_code, alpha3_code, name) VALUES ('MV','MDV','Maldives');
INSERT INTO local_ole.uc_countries (alpha2_code, alpha3_code, name) VALUES ('MW','MWI','Malawi');
INSERT INTO local_ole.uc_countries (alpha2_code, alpha3_code, name) VALUES ('MX','MEX','Mexico');
INSERT INTO local_ole.uc_countries (alpha2_code, alpha3_code, name) VALUES ('MY','MYS','Malaysia');
INSERT INTO local_ole.uc_countries (alpha2_code, alpha3_code, name) VALUES ('MZ','MOZ','Mozambique');
INSERT INTO local_ole.uc_countries (alpha2_code, alpha3_code, name) VALUES ('NA','NAM','Namibia');
INSERT INTO local_ole.uc_countries (alpha2_code, alpha3_code, name) VALUES ('NC','NCL','New Caledonia');
INSERT INTO local_ole.uc_countries (alpha2_code, alpha3_code, name) VALUES ('NE','NER','Niger');
INSERT INTO local_ole.uc_countries (alpha2_code, alpha3_code, name) VALUES ('NF','NFK','Norfolk Island');
INSERT INTO local_ole.uc_countries (alpha2_code, alpha3_code, name) VALUES ('NG','NGA','Nigeria');
INSERT INTO local_ole.uc_countries (alpha2_code, alpha3_code, name) VALUES ('NI','NIC','Nicaragua');
INSERT INTO local_ole.uc_countries (alpha2_code, alpha3_code, name) VALUES ('NL','NLD','Netherlands');
INSERT INTO local_ole.uc_countries (alpha2_code, alpha3_code, name) VALUES ('NO','NOR','Norway');
INSERT INTO local_ole.uc_countries (alpha2_code, alpha3_code, name) VALUES ('NP','NPL','Nepal');
INSERT INTO local_ole.uc_countries (alpha2_code, alpha3_code, name) VALUES ('NR','NRU','Nauru');
INSERT INTO local_ole.uc_countries (alpha2_code, alpha3_code, name) VALUES ('NU','NIU','Niue');
INSERT INTO local_ole.uc_countries (alpha2_code, alpha3_code, name) VALUES ('NZ','NZL','New Zealand');
INSERT INTO local_ole.uc_countries (alpha2_code, alpha3_code, name) VALUES ('OM','OMN','Oman');
INSERT INTO local_ole.uc_countries (alpha2_code, alpha3_code, name) VALUES ('PA','PAN','Panama');
INSERT INTO local_ole.uc_countries (alpha2_code, alpha3_code, name) VALUES ('PE','PER','Peru');
INSERT INTO local_ole.uc_countries (alpha2_code, alpha3_code, name) VALUES ('PF','PYF','French Polynesia');
INSERT INTO local_ole.uc_countries (alpha2_code, alpha3_code, name) VALUES ('PG','PNG','Papua New Guinea');
INSERT INTO local_ole.uc_countries (alpha2_code, alpha3_code, name) VALUES ('PH','PHL','Philippines');
INSERT INTO local_ole.uc_countries (alpha2_code, alpha3_code, name) VALUES ('PK','PAK','Pakistan');
INSERT INTO local_ole.uc_countries (alpha2_code, alpha3_code, name) VALUES ('PL','POL','Poland');
INSERT INTO local_ole.uc_countries (alpha2_code, alpha3_code, name) VALUES ('PM','SPM','Saint Pierre And Miquelon');
INSERT INTO local_ole.uc_countries (alpha2_code, alpha3_code, name) VALUES ('PN','PCN','Pitcairn');
INSERT INTO local_ole.uc_countries (alpha2_code, alpha3_code, name) VALUES ('PR','PRI','Puerto Rico');
INSERT INTO local_ole.uc_countries (alpha2_code, alpha3_code, name) VALUES ('PS','PSE','Palestinian Territory, Occupied');
INSERT INTO local_ole.uc_countries (alpha2_code, alpha3_code, name) VALUES ('PT','PRT','Portugal');
INSERT INTO local_ole.uc_countries (alpha2_code, alpha3_code, name) VALUES ('PW','PLW','Palau');
INSERT INTO local_ole.uc_countries (alpha2_code, alpha3_code, name) VALUES ('PY','PRY','Paraguay');
INSERT INTO local_ole.uc_countries (alpha2_code, alpha3_code, name) VALUES ('QA','QAT','Qatar');
INSERT INTO local_ole.uc_countries (alpha2_code, alpha3_code, name) VALUES ('RE','REU','Réunion');
INSERT INTO local_ole.uc_countries (alpha2_code, alpha3_code, name) VALUES ('RO','ROU','Romania');
INSERT INTO local_ole.uc_countries (alpha2_code, alpha3_code, name) VALUES ('RS','SRB','Serbia');
INSERT INTO local_ole.uc_countries (alpha2_code, alpha3_code, name) VALUES ('RU','RUS','Russian Federation');
INSERT INTO local_ole.uc_countries (alpha2_code, alpha3_code, name) VALUES ('RW','RWA','Rwanda');
INSERT INTO local_ole.uc_countries (alpha2_code, alpha3_code, name) VALUES ('SA','SAU','Saudi Arabia');
INSERT INTO local_ole.uc_countries (alpha2_code, alpha3_code, name) VALUES ('SB','SLB','Solomon Islands');
INSERT INTO local_ole.uc_countries (alpha2_code, alpha3_code, name) VALUES ('SC','SYC','Seychelles');
INSERT INTO local_ole.uc_countries (alpha2_code, alpha3_code, name) VALUES ('SD','SDN','Sudan');
INSERT INTO local_ole.uc_countries (alpha2_code, alpha3_code, name) VALUES ('SE','SWE','Sweden');
INSERT INTO local_ole.uc_countries (alpha2_code, alpha3_code, name) VALUES ('SG','SGP','Singapore');
INSERT INTO local_ole.uc_countries (alpha2_code, alpha3_code, name) VALUES ('SH','SHN','St. Helena, Ascension, Tristan Da Cunha');
INSERT INTO local_ole.uc_countries (alpha2_code, alpha3_code, name) VALUES ('SI','SVN','Slovenia');
INSERT INTO local_ole.uc_countries (alpha2_code, alpha3_code, name) VALUES ('SJ','SJM','Svalbard And Jan Mayen');
INSERT INTO local_ole.uc_countries (alpha2_code, alpha3_code, name) VALUES ('SK','SVK','Slovakia');
INSERT INTO local_ole.uc_countries (alpha2_code, alpha3_code, name) VALUES ('SL','SLE','Sierra Leone');
INSERT INTO local_ole.uc_countries (alpha2_code, alpha3_code, name) VALUES ('SM','SMR','San Marino');
INSERT INTO local_ole.uc_countries (alpha2_code, alpha3_code, name) VALUES ('SN','SEN','Senegal');
INSERT INTO local_ole.uc_countries (alpha2_code, alpha3_code, name) VALUES ('SO','SOM','Somalia');
INSERT INTO local_ole.uc_countries (alpha2_code, alpha3_code, name) VALUES ('SR','SUR','Suriname');
INSERT INTO local_ole.uc_countries (alpha2_code, alpha3_code, name) VALUES ('ST','STP','Sao Tome and Principe');
INSERT INTO local_ole.uc_countries (alpha2_code, alpha3_code, name) VALUES ('SV','SLV','El Salvador');
INSERT INTO local_ole.uc_countries (alpha2_code, alpha3_code, name) VALUES ('SY','SYR','Syrian Arab Republic');
INSERT INTO local_ole.uc_countries (alpha2_code, alpha3_code, name) VALUES ('SZ','SWZ','Swaziland');
INSERT INTO local_ole.uc_countries (alpha2_code, alpha3_code, name) VALUES ('TC','TCA','Turks and Caicos Islands');
INSERT INTO local_ole.uc_countries (alpha2_code, alpha3_code, name) VALUES ('TD','TCD','Chad');
INSERT INTO local_ole.uc_countries (alpha2_code, alpha3_code, name) VALUES ('TF','ATF','French Southern Territories');
INSERT INTO local_ole.uc_countries (alpha2_code, alpha3_code, name) VALUES ('TG','TGO','Togo');
INSERT INTO local_ole.uc_countries (alpha2_code, alpha3_code, name) VALUES ('TH','THA','Thailand');
INSERT INTO local_ole.uc_countries (alpha2_code, alpha3_code, name) VALUES ('TJ','TJK','Tajikistan');
INSERT INTO local_ole.uc_countries (alpha2_code, alpha3_code, name) VALUES ('TK','TKL','Tokelau');
INSERT INTO local_ole.uc_countries (alpha2_code, alpha3_code, name) VALUES ('TL','TLS','Timor-Leste');
INSERT INTO local_ole.uc_countries (alpha2_code, alpha3_code, name) VALUES ('TM','TKM','Turkmenistan');
INSERT INTO local_ole.uc_countries (alpha2_code, alpha3_code, name) VALUES ('TN','TUN','Tunisia');
INSERT INTO local_ole.uc_countries (alpha2_code, alpha3_code, name) VALUES ('TO','TON','Tonga');
INSERT INTO local_ole.uc_countries (alpha2_code, alpha3_code, name) VALUES ('TR','TUR','Turkey');
INSERT INTO local_ole.uc_countries (alpha2_code, alpha3_code, name) VALUES ('TT','TTO','Trinidad and Tobago');
INSERT INTO local_ole.uc_countries (alpha2_code, alpha3_code, name) VALUES ('TV','TUV','Tuvalu');
INSERT INTO local_ole.uc_countries (alpha2_code, alpha3_code, name) VALUES ('TW','TWN','Taiwan, Province Of China');
INSERT INTO local_ole.uc_countries (alpha2_code, alpha3_code, name) VALUES ('TZ','TZA','Tanzania, United Republic of');
INSERT INTO local_ole.uc_countries (alpha2_code, alpha3_code, name) VALUES ('UA','UKR','Ukraine');
INSERT INTO local_ole.uc_countries (alpha2_code, alpha3_code, name) VALUES ('UG','UGA','Uganda');
INSERT INTO local_ole.uc_countries (alpha2_code, alpha3_code, name) VALUES ('UM','UMI','United States Minor Outlying Islands');
INSERT INTO local_ole.uc_countries (alpha2_code, alpha3_code, name) VALUES ('US','USA','United States');
INSERT INTO local_ole.uc_countries (alpha2_code, alpha3_code, name) VALUES ('UY','URY','Uruguay');
INSERT INTO local_ole.uc_countries (alpha2_code, alpha3_code, name) VALUES ('UZ','UZB','Uzbekistan');
INSERT INTO local_ole.uc_countries (alpha2_code, alpha3_code, name) VALUES ('VA','VAT','Holy See (Vatican City State),');
INSERT INTO local_ole.uc_countries (alpha2_code, alpha3_code, name) VALUES ('VC','VCT','Saint Vincent And The Grenedines');
INSERT INTO local_ole.uc_countries (alpha2_code, alpha3_code, name) VALUES ('VE','VEN','Venezuela, Bolivarian Republic of');
INSERT INTO local_ole.uc_countries (alpha2_code, alpha3_code, name) VALUES ('VG','VGB','Virgin Islands, British');
INSERT INTO local_ole.uc_countries (alpha2_code, alpha3_code, name) VALUES ('VI','VIR','Virgin Islands, U.S.');
INSERT INTO local_ole.uc_countries (alpha2_code, alpha3_code, name) VALUES ('VN','VNM','Viet Nam');
INSERT INTO local_ole.uc_countries (alpha2_code, alpha3_code, name) VALUES ('VU','VUT','Vanuatu');
INSERT INTO local_ole.uc_countries (alpha2_code, alpha3_code, name) VALUES ('WF','WLF','Wallis and Futuna');
INSERT INTO local_ole.uc_countries (alpha2_code, alpha3_code, name) VALUES ('WS','WSM','Samoa');
INSERT INTO local_ole.uc_countries (alpha2_code, alpha3_code, name) VALUES ('YE','YEM','Yemen');
INSERT INTO local_ole.uc_countries (alpha2_code, alpha3_code, name) VALUES ('YT','MYT','Mayotte');
INSERT INTO local_ole.uc_countries (alpha2_code, alpha3_code, name) VALUES ('ZA','ZAF','South Africa');
INSERT INTO local_ole.uc_countries (alpha2_code, alpha3_code, name) VALUES ('ZM','ZMB','Zambia');
INSERT INTO local_ole.uc_countries (alpha2_code, alpha3_code, name) VALUES ('ZW','ZWE','Zimbabwe');
INSERT INTO local_ole.uc_countries (alpha2_code, alpha3_code, name) VALUES ('ZZ','ZZZ','Other Countries');
ALTER TABLE local_ole.uc_countries
    ADD CONSTRAINT uc_countries_pkey PRIMARY KEY (alpha2_code);
